<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="AI 專屬管家 - 多功能生活整合助理：包含智能記事本、待辦清單、旅遊行程規劃、Google Maps導航與智慧記帳功能。">
    <title>AI 專屬管家 | 智能生活助理</title>
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Noto+Sans+TC:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Google Material Symbols Rounded -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <!-- Mobile Menu Toggle -->
    <button class="mobile-toggle" onclick="toggleMobileMenu()" aria-label="切換選單">
        <span class="material-symbols-rounded">menu</span>
    </button>

    <div id="app">
        <!-- Sidebar Navigation -->
        <aside class="sidebar" id="sidebar">
            <div class="brand">
                <span class="material-symbols-rounded">stars</span>
                <h1>AI 專屬管家</h1>
            </div>
            
            <nav class="nav-menu">
                <div class="nav-item active" onclick="showSection('notepad', this)">
                    <span class="material-symbols-rounded">edit_note</span>
                    <span>記事與公告</span>
                </div>
                <div class="nav-item" onclick="showSection('todo', this)">
                    <span class="material-symbols-rounded">task_alt</span>
                    <span>待辦追蹤</span>
                </div>
                <div class="nav-item" onclick="showSection('planner', this)">
                    <span class="material-symbols-rounded">travel_explore</span>
                    <span>行程與路線</span>
                </div>
                <div class="nav-item" onclick="showSection('accounting', this)">
                    <span class="material-symbols-rounded">account_balance_wallet</span>
                    <span>智慧記帳</span>
                </div>
            </nav>
        </aside>

        <!-- Main Content Area -->
        <main class="main-content">
            
            <!-- 1. Notepad Section -->
            <section id="notepad" class="section-container active">
                <div class="top-bar">
                    <div class="greeting">
                        <h2 id="greeting-text">你好，<br>美好的一天開始了</h2>
                        <p>專注於當下，紀錄每一個靈感瞬間。</p>
                    </div>
                </div>

                <div class="glass-card">
                    <div class="card-title">
                        <span class="material-symbols-rounded">history_edu</span>
                        隨身記事本
                    </div>
                    <div class="input-group">
                        <textarea id="note-input" rows="6" placeholder="這是您的專屬紀錄空間，歡迎寫下任何事項！&#10;&#10;- 支援多行輸入&#10;- 自動儲存"></textarea>
                    </div>
                    <button onclick="saveNote()">
                        <span class="material-symbols-rounded">save</span>
                        儲存紀錄
                    </button>
                    <!-- Display Area -->
                    <div id="note-list" class="note-list"></div>
                </div>
            </section>

            <!-- 2. To-do List Section -->
            <section id="todo" class="section-container">
                <div class="top-bar">
                    <div class="greeting">
                        <h2>待辦追蹤</h2>
                        <p>有條不紊，完成每天的目標</p>
                    </div>
                </div>

                <div class="glass-card">
                    <div class="card-title">
                        <span class="material-symbols-rounded">checklist</span>
                        今日任務清單
                    </div>
                    
                    <div class="todo-input-wrap">
                        <input type="text" id="todo-input" placeholder="準備做些什麼呢？ 輸入新任務..." onkeypress="handleTodoKeyPress(event)">
                        <button onclick="addTodo()" style="white-space: nowrap;">
                            <span class="material-symbols-rounded">add_task</span>
                            新增任務
                        </button>
                    </div>
                    
                    <div id="todo-list" class="todo-list">
                        <!-- Todo items generated by JS -->
                    </div>
                </div>
            </section>

            <!-- 3. Planner & Route Section -->
            <section id="planner" class="section-container">
                <div class="top-bar">
                    <div class="greeting">
                        <h2>行程與路線</h2>
                        <p>為下一次的冒險做好準備</p>
                    </div>
                </div>
                
                <div class="tabs">
                    <button class="tab-btn active" onclick="showTab('tab-itinerary', this)">旅遊規劃</button>
                    <button class="tab-btn" onclick="showTab('tab-route', this)">地點導航</button>
                </div>

                <!-- 3.1 Travel Planner Tab -->
                <div id="tab-itinerary" class="tab-content active glass-card">
                    <div class="card-title">
                        <span class="material-symbols-rounded">flight_takeoff</span>
                        專屬行程設計
                    </div>
                    <div class="grid-3">
                        <div class="input-group">
                            <label>國家</label>
                            <input type="text" id="plan-country" placeholder="例如：日本">
                        </div>
                        <div class="input-group">
                            <label>城市 / 地區</label>
                            <input type="text" id="plan-destination" placeholder="例如：東京">
                        </div>
                        <div class="input-group">
                            <label>旅遊天數</label>
                            <input type="number" id="plan-days" value="3" min="1" max="30">
                        </div>
                        <div class="input-group">
                            <label>同行人數</label>
                            <input type="number" id="plan-people" value="2" min="1">
                        </div>
                        <div class="input-group">
                            <label>總預算 (TWD)</label>
                            <input type="number" id="plan-budget" placeholder="例如：50000">
                        </div>
                        <div class="input-group">
                            <label>主要交通方式</label>
                            <select id="plan-transport">
                                <option value="大眾運輸">🚆 大眾運輸 (地鐵/公車)</option>
                                <option value="自駕">🚗 自駕租車</option>
                                <option value="包車">🚐 專車接送 / 包車</option>
                            </select>
                        </div>
                    </div>
                    <button onclick="generateItinerary()" style="margin-top: 1rem; width: 100%;">
                        <span class="material-symbols-rounded">auto_awesome</span>
                        AI 智能生成行程
                    </button>
                    
                    <div id="itinerary-result" style="display: none;">
                        <div id="itinerary-content"></div>
                    </div>
                </div>

                <!-- 3.2 Route Planning Tab -->
                <div id="tab-route" class="tab-content glass-card">
                    <div class="card-title">
                        <span class="material-symbols-rounded">map</span>
                        智能路線導航
                    </div>
                    <div class="grid-2">
                        <div class="input-group">
                            <label>出發地 (名稱或地址，留白表示目前位置)</label>
                            <input type="text" id="route-from" placeholder="例如：台北車站">
                        </div>
                        <div class="input-group">
                            <label>目的地 (名稱或地址)</label>
                            <input type="text" id="route-to" placeholder="例如：台北101">
                        </div>
                    </div>
                    <div class="input-group">
                        <label>導航交通方式</label>
                        <select id="route-mode">
                            <option value="transit">🚇 大眾運輸</option>
                            <option value="driving">🚗 開車</option>
                            <option value="walking">🚶 步行</option>
                            <option value="bicycling">🚲 騎車</option>
                        </select>
                    </div>
                    <button onclick="openGoogleMaps()" style="margin-top: 1rem; width: 100%; background: #23a6d5;">
                        <span class="material-symbols-rounded">explore</span>
                        在 Google Maps 規劃最佳路線
                    </button>
                </div>
            </section>

            <!-- 4. Accounting Section -->
            <section id="accounting" class="section-container">
                <div class="top-bar">
                    <div class="greeting">
                        <h2>智慧記帳</h2>
                        <p>清楚掌握每一筆收支狀況</p>
                    </div>
                </div>

                <div class="glass-card">
                    <div class="card-title">
                        <span class="material-symbols-rounded">payments</span>
                        新增紀錄
                    </div>
                    
                    <div class="acc-form">
                        <div class="input-group" style="margin-bottom: 0;">
                            <label>日期</label>
                            <input type="date" id="acc-date">
                        </div>
                        <div class="input-group" style="margin-bottom: 0;">
                            <label>收支</label>
                            <select id="acc-type">
                                <option value="expense">支出</option>
                                <option value="income">收入</option>
                            </select>
                        </div>
                        <div class="input-group" style="margin-bottom: 0;">
                            <label>類別</label>
                            <select id="acc-category">
                                <option value="飲食">🍽️ 飲食</option>
                                <option value="交通">🚌 交通</option>
                                <option value="購物">🛍️ 購物</option>
                                <option value="娛樂">🎮 娛樂</option>
                                <option value="薪資">💰 薪資</option>
                                <option value="其他">📌 其他</option>
                            </select>
                        </div>
                        <div class="input-group" style="margin-bottom: 0;">
                            <label>金額 (TWD)</label>
                            <input type="number" id="acc-amount" placeholder="金額..." min="1">
                        </div>
                    </div>
                    
                    <div class="input-group">
                        <label>備註 (選填)</label>
                        <input type="text" id="acc-note" placeholder="例如：午餐拉麵、搭捷運...">
                    </div>
                    
                    <button onclick="addAccountRecord()" style="margin-top: 1rem;">
                        <span class="material-symbols-rounded">add_circle</span>
                        儲存帳務紀錄
                    </button>
                </div>

                <div class="glass-card">
                    <div class="card-title">
                        <span class="material-symbols-rounded">receipt_long</span>
                        帳務歷史紀錄
                    </div>
                    <div class="acc-table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th width="15%">日期</th>
                                    <th width="10%">收支</th>
                                    <th width="15%">類別</th>
                                    <th width="35%">備註</th>
                                    <th width="15%">金額</th>
                                    <th width="10%">操作</th>
                                </tr>
                            </thead>
                            <tbody id="account-list">
                                <!-- Generated by JS -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </main>
    </div>

    <!-- Custom Script -->
    <script src="script.js"></script>
</body>
</html>